// automatically generated by the FlatBuffers compiler, do not modify

package ROC;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ActionInfo extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static ActionInfo getRootAsActionInfo(ByteBuffer _bb) { return getRootAsActionInfo(_bb, new ActionInfo()); }
  public static ActionInfo getRootAsActionInfo(ByteBuffer _bb, ActionInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ActionInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String uavId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uavIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer uavIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String latitude() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer latitudeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer latitudeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String longitude() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer longitudeAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer longitudeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createActionInfo(FlatBufferBuilder builder,
      int uav_idOffset,
      int latitudeOffset,
      int longitudeOffset) {
    builder.startTable(3);
    ActionInfo.addLongitude(builder, longitudeOffset);
    ActionInfo.addLatitude(builder, latitudeOffset);
    ActionInfo.addUavId(builder, uav_idOffset);
    return ActionInfo.endActionInfo(builder);
  }

  public static void startActionInfo(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addUavId(FlatBufferBuilder builder, int uavIdOffset) { builder.addOffset(0, uavIdOffset, 0); }
  public static void addLatitude(FlatBufferBuilder builder, int latitudeOffset) { builder.addOffset(1, latitudeOffset, 0); }
  public static void addLongitude(FlatBufferBuilder builder, int longitudeOffset) { builder.addOffset(2, longitudeOffset, 0); }
  public static int endActionInfo(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishActionInfoBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedActionInfoBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ActionInfo get(int j) { return get(new ActionInfo(), j); }
    public ActionInfo get(ActionInfo obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

